# Generated by Django 6.0.3 on 2026-03-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interested_fields',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_category',
            field=models.CharField(blank=True, choices=[('job', 'Job'), ('internship', 'Internship'), ('both', 'Both')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_location',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('any', 'Any')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
