# Generated by Django 6.0.3 on 2026-03-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('category', models.CharField(choices=[('job', 'Job'), ('internship', 'Internship')], max_length=20)),
                ('location', models.CharField(default='Not specified', max_length=255)),
                ('description', models.TextField()),
                ('apply_link', models.URLField()),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
