# Generated by Django 6.0.3 on 2026-03-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('job', 'Job'), ('internship', 'Internship')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='deadline',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=20),
        ),
    ]
