# Generated by Django 6.0.3 on 2026-03-06 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_alter_opportunity_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='eligible_programs',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='eligible_years',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='field_tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='minimum_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='minimum_requirements_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='apply_link',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'opportunity'), name='unique_user_opportunity_application')],
            },
        ),
    ]
